apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/gompangii/dispatcher-service/k8s?ref=main

patches:
  - path: patch-env.yml
    target:
      kind: Deployment
      name: dispatcher-service

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: dispatcher-config

images:
  - name: dispatcher-service
    newName: docker.io/gompangii/dispatcher-service
    newTag: latest

replicas:
  - name: dispatcher-service
    count: 1
