version: "3.8"
services:
  catalog-service:
    image: "gompangii/catalog-service:latest"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:mariadb://192.168.56.40:3306/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata