version: "3.8"
services:
  catalog-service:
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:mariadb://192.168.56.40:3306/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata