apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/gompangii/order-service/k8s?ref=main

patches:
  - path: patch-env.yml
    target:
      kind: Deployment
      name: order-service

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: order-config

images:
  - name: order-service
    newName: docker.io/gompangii/order-service
    newTag: latest

replicas:
  - name: order-service
    count: 1
